/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('game_list').del()
  await knex('game_list').insert([
    {user_id: 1, title: 'Super Mario Bros. 3', release_date: '1990-02-12', developer: 'Nintendo', description: `Super Mario Bros. 3 is a 2D action-adventure platform game for the Famicom and NES and is the fourth installment in the Super Mario series. It was released for consoles in Japan on October 23, 1988; in North America on February 12, 1990; and in Europe and Australia on August 29, 1991. Prior to its North American release on the NES, Super Mario Bros. 3 was ported to the Nintendo PlayChoice-10.[6] Being the first game in the series since Super Mario Bros. not to derive its gameplay from another game, Super Mario Bros. 3 retains the same level-based platformer mechanics of previous titles. These core mechanics are iterated upon, featuring greatly expanded levels, several new power-ups, new enemies and bosses, a more fleshed-out multiplayer mode, a world map, and many optional levels and secrets. The game has gone on to become one of the most influential titles for the Super Mario franchise, and several elements introduced in this title have since become franchise mainstays, including landscape-themed worlds, the Koopalings, airships, and Toad Houses.`},
    {user_id: 2, title: '12Riven: The Psi-Climinal of Integral', release_date: '2008-03-13', developer: 'KID', description: `12Riven: The Psi-Climinal of Integral[a] is a visual novel video game developed by KID, CyberFront, and SDR Project, and released on March 13, 2008, for the PlayStation 2 and April 16, 2009, for the PlayStation Portable. There is a regular edition, and a special edition which included the game's original soundtrack. KID are known for producing the Memories Off series, and the Infinity series which includes Never 7: The End of Infinity, Ever 17: The Out of Infinity, and Remember 11: The Age of Infinity. When KID declared bankruptcy in November 2006, production on the game was halted until CyberFront took over and resumed production.`},
    {user_id: 1, title: 'Robotics;Notes', release_date: '2020-10-13', developer: '5pb.', description: `Robotics;Notes is a visual novel video game developed by 5pb. It is the third main game in the Science Adventure series, following Chaos;Head and Steins;Gate, and is described by the developers as an "Augmented Science Adventure". The game was originally released by 5pb. in Japan on the PlayStation 3 and Xbox 360 in 2012; the enhanced version Robotics;Notes Elite was released for PlayStation Vita in 2014, and for Nintendo Switch and PlayStation 4 in 2019. An English version of Robotics;Notes Elite was released by Spike Chunsoft in 2020 for Microsoft Windows, Nintendo Switch and PlayStation 4.`},
    {user_id: 2, title: 'Tekken 4', release_date: '2002-09-23', developer: 'Namco', description: `Tekken 4 (鉄拳4) is a fighting game developed and published by Namco as the fourth main and fifth installment in the Tekken series, following the release of the non-canon titled Tekken Tag Tournament in 1999. It was released on arcades in 2001, and on the PlayStation 2 in 2002.`},
    {user_id: 1, title: 'Mario Kart 8', release_date: '2014-05-29', developer: 'Nintendo', description: `Mario Kart 8 is a 2014 kart racing game developed and published by Nintendo for the Wii U. It retains the gameplay of previous games in the Mario Kart series, with players controlling a Mario franchise character in races around tracks. Tracks are themed around locales from the Super Mario platform series and are populated with power-ups that help players gain advantages in races. Different difficulties are selectable prior to a race; harder difficulties make gameplay faster. In the new anti-gravity sequences, players drive on walls and ceilings. Mario Kart 8 contains a variety of single-player and local and online multiplayer games modes, including Grand Prix racing and arena-based battle modes.`},
    {user_id: 1, title: 'Hollow Knight', release_date: '2017-02-24', developer: 'Team Cherry', description: `Hollow Knight is a 2017 Metroidvania video game developed and published by independent developer Team Cherry. In the game, the player controls the Knight, a nameless insectoid warrior, who explores Hallownest, a fallen kingdom plagued by a supernatural disease, known as the infection. The game is set in diverse subterranean locations, featuring friendly and hostile insectoid characters and numerous bosses. Players have the opportunity to unlock new abilities as they explore each location, along with pieces of lore and flavour text that are spread throughout the kingdom.`},
    ]);
};
